// Generated by CoffeeScript 1.6.3
var logger, moment, _;

logger = require('./logger');

_ = require('underscore');

moment = require('moment');

_.mixin({
  log: function() {
    return logger.apply(logger, arguments);
  },
  date: function(dateString, format) {
    if (!dateString) {
      dateString = new Date();
    }
    if (!format) {
      format = "MM/DD/YYYY hh:mm:ss a";
    }
    return moment(dateString).format(format);
  },
  calendar: function(dateString) {
    return moment(dateString).calendar();
  },
  age: function(dateString) {
    return moment(dateString).fromNow();
  },
  dayOfMonth: function(dateString) {
    return _.date(dateString, "D");
  },
  date2d: function(dateString) {
    return _.date(dateString, "DD");
  },
  month2d: function(dateString) {
    return _.date(dateString, "MM");
  },
  monthAbbr: function(dateString) {
    return _.date(dateString, "MMM");
  },
  monthFull: function(dateString) {
    return _.date(dateString, "MMMM");
  },
  year: function(dateString) {
    return _.date(dateString, "YYYY");
  },
  sha_stub: function(sha_hash) {
    return sha_hash.substring(0, 6);
  }
});

module.exports = _;
